#!/bin/env bash
export _BPXK_AUTOCVT=ON
set -x
cd $(/bin/dirname $0) || exit 99
exec 2>&1
type cob2 2>/dev/null
if [[ $? -eq 0 ]]; then
	cob2 -q64 -vV -comprc_ok=8 -q"list,LP(64)" -qexportall -c xd.cbl
	cob2 -Wl,dll,lp64 -o XDDLL xd.o
else
	echo COBOL compiler driver cob2 not found. using precompiled objects
	../cobol-objs/extract.sh
fi
go build
./example-cobol-cgo
