#!/bin/env bash
set -x
set -e
export _BPXK_AUTOCVT=ON
cd $(/bin/dirname $0) || exit 99
exec 2>&1
unset COBDIR
unset COB2
for d in V6R4M0 V6R3M0 V6R2M0 V6R1M0 V5R2M0; do
	if [[ -d "/usr/lpp/IBM/cobol/$d/" ]]; then
		COBDIR="/usr/lpp/IBM/cobol/$d/"
		if [[ -x "$COBDIR/bin/cob2" ]]; then
			COB2="/usr/lpp/IBM/cobol/$d/bin/cob2"
			break
		fi
	fi
done
if [[ -z "$COB2" ]]; then
	echo COBOL compiler driver cob2 not found. 
	exit 1
else
	echo $d
        C89_L6SYSIX='CEE.SCEELIB(CELQV004):CEE.SCEELIB(CELQS003)' STEPLIB=IGY.${d}.SIGYCOMP "$COB2" -q32 -comprc_ok=8 -o pfix pfix.cbl
fi
go build gocal.go
./gocal << END
1/3
222+(2345*12345553.7/7)
(7*34)+(1333445/7.23)
END
