#!/bin/env bash
set -x
set -e
export _BPXK_AUTOCVT=ON
cd $(/bin/dirname $0) || exit 99
exec 2>&1
unset COBDIR
unset COB2
for d in V6R4M0 V6R3M0 V6R2M0 V6R1M0 V5R2M0; do
	if [[ -d "/usr/lpp/IBM/cobol/$d/" ]]; then
		COBDIR="/usr/lpp/IBM/cobol/$d/"
		if [[ -x "$COBDIR/bin/cob2" ]]; then
			COB2="/usr/lpp/IBM/cobol/$d/bin/cob2"
			break
		fi
	fi
done
if [[ -z "$COB2" ]]; then
	echo COBOL compiler driver cob2 not found. using precompiled objects
	../cobol-objs/extract.sh
else

	STEPLIB=IGY.V6R4M0.SIGYCOMP "$COB2" -q64 -vV -comprc_ok=8 -q"list,LP(64)" -qexportall -c xd.cbl
	_C89_L6SYSIX='CEE.SCEELIB(CELQV004):CEE.SCEELIB(CELQS003)' "$COB2" -Wl,dll,lp64 -o XDDLL xd.o
fi
go build
./example-cobol
